# Generated by Django 4.2.5 on 2023-09-18 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfierros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='titulo_tag',
            field=models.CharField(default='BlogFierros', max_length=255),
        ),
    ]
