# Generated by Django 4.2.5 on 2023-09-21 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appfierros', '0005_category_post_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
